#!/usr/bin/python3
import sys

def factorize_numbers(filename):
    with open(filename, 'r') as f:
        for line in f:
            num = int(line)
            for i in range(2, num // 2 + 1):
                if num % i == 0:
                    print(f"{num}={i}*{num // i}")
                    break

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        factorize_numbers(sys.argv[1])

